/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./resources/js/App.vue')['default']
    AuthHero: typeof import('./resources/js/modules/auth/components/AuthHero.vue')['default']
    CertificateRequirementsCard: typeof import('./resources/js/modules/certificates/components/CertificateRequirementsCard.vue')['default']
    CertificateStatusCard: typeof import('./resources/js/modules/certificates/components/CertificateStatusCard.vue')['default']
    CertificatesView: typeof import('./resources/js/modules/certificates/views/CertificatesView.vue')['default']
    CertificateUploadForm: typeof import('./resources/js/modules/certificates/components/CertificateUploadForm.vue')['default']
    ContingencyGuide: typeof import('./resources/js/modules/contingency/components/ContingencyGuide.vue')['default']
    ContingencyStatusCards: typeof import('./resources/js/modules/contingency/components/ContingencyStatusCards.vue')['default']
    ContingencyView: typeof import('./resources/js/modules/contingency/views/ContingencyView.vue')['default']
    CreateDteModal: typeof import('./resources/js/modules/dtes/components/CreateDteModal.vue')['default']
    DashboardMetrics: typeof import('./resources/js/modules/dashboard/components/DashboardMetrics.vue')['default']
    DashboardView: typeof import('./resources/js/modules/dashboard/views/DashboardView.vue')['default']
    DteDataTable: typeof import('./resources/js/modules/dtes/components/DteDataTable.vue')['default']
    DtesView: typeof import('./resources/js/modules/dtes/views/DtesView.vue')['default']
    LayoutAuthenticated: typeof import('./resources/js/layouts/LayoutAuthenticated.vue')['default']
    LayoutGuest: typeof import('./resources/js/layouts/LayoutGuest.vue')['default']
    LoginForm: typeof import('./resources/js/guess/modules/login/components/LoginForm.vue')['default']
    LoginView: typeof import('./resources/js/guess/modules/login/views/LoginView.vue')['default']
    MhCredentialsForm: typeof import('./resources/js/modules/mh-credentials/components/MhCredentialsForm.vue')['default']
    MhCredentialsStatusCard: typeof import('./resources/js/modules/mh-credentials/components/MhCredentialsStatusCard.vue')['default']
    MhCredentialsView: typeof import('./resources/js/modules/mh-credentials/views/MhCredentialsView.vue')['default']
    MyProfileView: typeof import('./resources/js/modules/profile/views/MyProfileView.vue')['default']
    OnboardingForm: typeof import('./resources/js/guess/modules/onboarding/components/OnboardingForm.vue')['default']
    OnboardingView: typeof import('./resources/js/guess/modules/onboarding/views/OnboardingView.vue')['default']
    ProfileHeaderCard: typeof import('./resources/js/modules/profile/components/ProfileHeaderCard.vue')['default']
    QueueTable: typeof import('./resources/js/modules/queue/components/QueueTable.vue')['default']
    QueueView: typeof import('./resources/js/modules/queue/views/QueueView.vue')['default']
    RecoveryForm: typeof import('./resources/js/modules/auth/components/RecoveryForm.vue')['default']
    RecoveryPasswordView: typeof import('./resources/js/modules/auth/views/RecoveryPasswordView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
